name: OrangeFox - Build - Test

on:
  workflow_dispatch:

jobs:
  build:
    name: 🦊 Building OrangeFox Recovery
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v4
              
    - name: OrangeFox Build
      uses: ./
      with:
        USER_NAME: 'detroit313x'
        USER_EMAIL: '37162313+detroit313x@users.noreply.github.com'
        DEVICE_TREE: 'git@github.com:detroit313x/device_tree_boston.git'
        DEVICE_TREE_BRANCH: '12.1'
        DEVICE_PATH: 'device/motorola/boston'
        DEVICE_NAME: 'boston'
        BUILD_TARGET: 'vendorboot'
        TG_CHAT_ID: '${{ secrets.TG_CHAT_ID }}'
        TG_TOKEN: '${{ secrets.TG_TOKEN }}'
        MAINTAINER_URL: 'https://i.ibb.co.com/8gyjXq06/maintainer.png'
        GH_RELEASE: 'false'
